export enum ErrorCode {
  TASK_NOT_FOUND = 'TASK_NOT_FOUND',
  TODO_LIST_NOT_FOUND = 'TODO_LIST_NOT_FOUND',
  SUBTASK_NOT_FOUND = 'SUBTASK_NOT_FOUND',
  GROUP_NOT_FOUND = 'GROUP_NOT_FOUND',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
