export enum ActivityType {
  TODO_LIST_CREATED = 'TODO_LIST_CREATED',
  TODO_CREATED = 'TODO_CREATED',
  TODO_COMPLETED = 'TODO_COMPLETED',
  TODO_UNCOMPLETED = 'TODO_UNCOMPLETED',
  SUBTASK_CREATED = 'SUBTASK_CREATED',
  SUBTASK_COMPLETED = 'SUBTASK_COMPLETED',
  SUBTASK_UNCOMPLETED = 'SUBTASK_UNCOMPLETED',
}

export enum ActivityEntityType {
  TODO_LIST = 'TODO_LIST',
  TODO = 'TODO',
  SUBTASK = 'SUBTASK',
}

export const DEFAULT_ACTIVITY_PAGE_SIZE = 50;
export const MAX_ACTIVITY_PAGE_SIZE = 100;
